### ISSUE TITLE
9. Xem chi tiết đơn hàng (QLĐH)

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#10]
- Giao diện: kế bên mỗi đơn hàng có một button "Chi tiết", giao diện chi tiết đơn hàng gồm các thông tin (Họ tên khách hàng, mã đơn hàng, số điện thoại, E-mail, địa chỉ giao hàng, ngày tạo đơn hàng, trạng thái, tổng tiền), phía dưới có 1 danh sách sản phẩm khách hàng đặt mua được hiển thị dưới dạng table gồm các thông tin (hình sản phẩm, tên sản phẩm, giá, số lượng, thành tiền).
- Xử lý: Load thông tin bao gồm họ tên khách hàng, số điện thoại, E-mail, địa chỉ giao hàng, ngày tạo đơn hàng, trạng thái, tổng tiền, load thông tin các sản phẩm khách hàng đặt mua bao gồm hình sản phẩm, tên sản phẩm, giá, số lượng, thành tiền.
- Lưu trữ: không có

**Comment by lamtrungnghia1202** [comment]
Đã hoàn thành
