### ISSUE TITLE
10. Xem chi tiết sản phẩm (Admin)

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#11]
Giao diện: một form sẽ hiện ra gồm các thông tin cơ bản của sản phẩm như: Tên sản phẩm, mô tả ngắn về sản phẩm, hình ảnh, video của sản phẩm, chất liệu, màu sắc.

Xử lí: click vào button Chi tiết nằm ở cuối ở danh sách của mỗi sản phẩm thì form chi tiết sản phẩm sẽ được hiển thị. Dữ liệu hiển thị được truy cập từ database

Lưu trữ: Không có

**Comment by admd1142** [comment]
Giao diện: một form sẽ hiện ra gồm các thông tin cơ bản của sản phẩm như: Tên sản phẩm, mô tả ngắn về sản phẩm, hình ảnh, video của sản phẩm, chất liệu, màu sắc.

Xử lí: click vào button Chi tiết nằm ở cuối ở danh sách của mỗi sản phẩm thì form chi tiết sản phẩm sẽ được hiển thị. Dữ liệu hiển thị được truy cập từ database

Lưu trữ: Không có

**Comment by admd1142** [comment]
đã nhận!

**Comment by admd1142** [comment]
đã hoàn thành
