### ISSUE TITLE
12. Xem chi tiết sản phẩm 

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#13]
- Giao diện: khi click vào một sản phẩm bất kỳ sẽ hiển thị thông tin chi tiết của sản phẩm. Phía bên trái sẽ là hình ảnh sản phẩm, phía bên phải sẽ hiển thị tên sản phẩm, giá sản phẩm, mô tả sản phẩm và phía dưới là button thêm vào giỏ hàng.
- Xử lý: Load thông tin bao gồm tên hình ảnh giá mô tả của sản phẩm lên giao diện và button thêm sản phẩm vào giỏ hàng
- Lưu trữ: không có

**Comment by obito0147** [comment]
đã nhận
