### ISSUE TITLE
14. Chuyển trạng thái của đơn hàng (QLĐH)

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#15]
- Giao diện: kế bên mỗi đơn hàng có một button "Cập nhật", giao diện cập nhật đơn hàng là 1 dialog bao gồm các trạng thái đơn hàng (Đang giao hàng, đã giao) được hiển thị dưới dạng option, bên dưới có 1 button "Lưu"
- Xử lý: Khi click vào button 'Lưu", đơn hàng sẽ được cập nhật trạng thái dựa vào index.
- Lưu trữ: Cập nhật thuộc tính trạng thái đơn hàng ở bảng hóa đơn bán

**Comment by lamtrungnghia1202** [comment]
Đã hoàn thành
