### ISSUE TITLE
15. Thêm sản phẩm (Admin)

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#16]
Giao diện: trong phần quản lí sản phẩm, button thêm sản phẩm nằm ở góc trên phải của cột bên phải, một form điền theo mẫu sẽ xuất hiện

Xử lý: phần input được nhập với các thông tin như: Tên sản phẩm, thông tin sản phẩm, hình ảnh,video của sản phẩm, chất liệu, màu sắc. Sau khi điền xong bạn sẽ xác nhận bằng button thêm sản phẩm

Lưu trữ: thông tin sản phẩm đã được nhập, update trong bảng CSDL

**Comment by admd1142** [comment]
Giao diện: trong phần quản lí sản phẩm, button thêm sản phẩm nằm ở góc trên phải của cột bên phải, một form điền theo mẫu sẽ xuất hiện

Xử lý: phần input được nhập với các thông tin như: Tên sản phẩm, thông tin sản phẩm, hình ảnh,video của sản phẩm, chất liệu, màu sắc. Sau khi điền xong bạn sẽ xác nhận bằng button thêm sản phẩm

Lưu trữ: thông tin sản phẩm đã được nhập, update trong bảng CSDL

**Comment by admd1142** [comment]
đã nhận!

**Comment by admd1142** [comment]
đã hoàn thành
