### ISSUE TITLE
18. Xóa sản phẩm trong giỏ hàng

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#19]
1. Giao diện: 

-	Hiển thị theo 1 cột với width:70%, display ở giữa màn hình.
-	Mỗi row là 1 div hiển thị thông tin của một sản phẩm trong giỏ hàng:
•	Mỗi row có 3 cột: cột đầu tiên hiển thị hình ảnh sản phẩm, bên dưới ảnh có button “Xóa” để xóa sản phẩm khỏi giỏ hàng. Cột thứ hai hiển thị thông tin của sản phẩm. Cột thứ ba hiển thị giá thành của sản phẩm.
•	Và 1 thẻ <div></div> chứa 1 thanh input và một button “-“ bên trái thanh input, một button “+” bên phải thanh input. Để cập nhật số lượng sản phẩm. display bên phải div.
-	Row cuối chứa tổng giá trị đơn hàng và một button “TIẾP THEO”. Để thới trang nhập thông tin giao hàng và thanh toán

2. Xử lý:

-	Sử dụng vòng lặp foreach để đọc dữ liệu của từng sản phẩm trong List<CartItem> đã được người dùng thêm vào.
-	Sử dụng LINQ để tính tổng số tiền của đơn hàng.
-	Sử dụng vòng lặp foreach để tính tổng số tiền của từng sản phẩm dựa vào số lượng và đơn giá.
-	Khi click button “Xóa”. Xóa sản phẩm khỏi List<CartItem> dựa vào index. Cập nhật lại tổng giá trị đơn hàng.
-	Khi click button “TIẾP THEO” chuyển tới trang nhập thông tin giao hàng và thanh toán.

3. Lưu trữ:

-	List<CartItem> được lưu trữ trong phiên làm việc bằng Session.

**Comment by ChiCuong002** [comment]
Đã hoàn thành
