### ISSUE TITLE
19. Tìm kiếm đơn hàng (QLĐH)

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#20]
- Giao diện: ở trang danh sách đơn đặt hàng có 1 thanh tìm kiếm dưới dạng silder để nhập liệu và 1 button  để submit.
- Xử lý: Load dữ liệu đơn hàng  theo từ khóa nhập vào từ View để hiển thị lên giao diện.
- Lưu trữ: không có

**Comment by lamtrungnghia1202** [comment]
Đã hoàn thành
