### ISSUE TITLE
20. Xóa sản phẩm (Admin)

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#21]
Giao diện: Tại mục quản lý sản phẩm, sẽ show ra danh sách sản phẩm với các thông tin cơ bản (mã, tên, số lượng) và luôn luôn sẽ có các nút button nằm ở cuối ( copy, sửa, xóa).

Xử lý: Khi ấn xóa sản phẩm, sẽ xuất hiện một thông báo alert với hai nút button
+ OK: sản phẩm sẽ bị ẩn đi và có thể khôi phục lại
+ Hủy: sẽ quay lại trang và không có chuyện gì xảy ra

Lưu trữ: xóa thông tin của sản phẩm trên csdl sau đó sẽ update trên CSDL

**Comment by admd1142** [comment]
Giao diện: Tại mục quản lý sản phẩm, sẽ show ra danh sách sản phẩm với các thông tin cơ bản (mã, tên, số lượng, ...) và luôn luôn sẽ có các nút button nằm ở cuối ( copy, sửa, xóa, ... ).

Xử lý: Khi ấn xóa sản phẩm, sẽ xuất hiện một thông báo alert với hai nút button
              + OK: sản phẩm sẽ bị ẩn đi và có thể khôi phục lại
              + Hủy: sẽ quay lại trang và không có chuyện gì xảy ra

Lưu trữ: xóa thông tin của sản phẩm trên csdl sau đó sẽ update trên CSDL

**Comment by admd1142** [comment]
đã nhận!

**Comment by admd1142** [comment]
đã hoàn thành
