### ISSUE TITLE
22. Tìm kiếm sản phẩm 

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#23]
- Giao diện: ở trang chủ và trang danh sách sản phẩm theo hãng sẽ có 1 thanh tìm kiếm phía dưới slider để nhập liệu và 1 nút button để submit.
- Xử lý: Load dữ liệu sản phẩm theo từ khóa nhập vào từ View hiển thị lên giao diện
- Lưu trữ: không có

**Comment by obito0147** [comment]
đã nhận

**Comment by obito0147** [comment]
đã hoàn thành
