### ISSUE TITLE
25. Cập nhật sản phẩm (Admin)

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#26]
Giao diện: Tại mục quản lý sản phẩm, sẽ show ra danh sách sản phẩm với các thông tin cơ bản (mã, tên, số lượng) và luôn luôn sẽ có các nút button nằm ở cuối ( copy, sửa, xóa).

Xử lý: khi chọn button Sửa, một form điền theo mẫu sẽ xuất hiện, bạn có thể sữa các thông tin như: tên sản phẩm, thông tin sản phẩm, hình ảnh, video của sản phẩm, chất liệu, màu sắc. Sau khi điền xong bạn sẽ xác nhận bằng button xác nhận sửa

Lưu trữ: điều chỉnh lại thông tin của sản phẩm sau đó update trên CSDL

**Comment by admd1142** [comment]
Giao diện: Tại mục quản lý sản phẩm, sẽ show ra danh sách sản phẩm với các thông tin cơ bản (mã, tên, số lượng, ...) và luôn luôn sẽ có các nút button nằm ở cuối ( copy, sửa, xóa, ... ).

Xử lý: khi chọn button Sửa, một form điền theo mẫu sẽ xuất hiện, bạn có thể sữa các thông tin như: tên sản phẩm, thông tin sản phẩm, hình ảnh, video của sản phẩm, chất liệu, màu sắc. Sau khi điền xong bạn sẽ  xác nhận bằng button xác nhận sửa

Lưu trữ: điều chỉnh lại thông tin của sản phẩm sau đó update trên CSDL

**Comment by admd1142** [comment]
đã nhận!

**Comment by admd1142** [comment]
đã hoàn thành
