### ISSUE TITLE
26. Xem thông tin cá nhân 

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#27]
- Giao diện: phía trên cùng là thanh navigation hiển thị các mục trang chủ, sản phẩm,đăng nhập và đăng ký, khi đăng nhập thành công sẽ hiển thị tên người dùng và đăng xuất thay cho đăng nhập và đăng ký. Phía dưới sẽ là chi tiết của tài khoản người dùng hiển thị dưới dạng danh sách như tên, ngày sinh, địa chỉ, số điện thoại, email phía dưới sẽ là footer
- Xử lý: Load dữ liệu của người dùng từ csdl lên giao diện
- Lưu trữ: không có

**Comment by obito0147** [comment]
đã nhận

**Comment by obito0147** [comment]
đã hoàn thành
