### ISSUE TITLE
2. Xem trang chủ 

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#3]
- Giao diện: trên cùng là thanh navigation thể hiện (trang chủ, sản phẩm, đăng nhập). Bên dưới là một slider để chạy quảng cáo. Phía dưới góc bên trái là khung tìm kiếm. Phía dưới nữa sẽ là 9 sản phẩm hiển thị theo ngày mới nhất. Cuối cùng là footer
- Xử lý: Chức năng đăng nhập khi click vào ở thanh navigation, Chức năng tìm kiếm và load sản phẩm từ csdl theo từ khóa tìm kiếm, Load sản 9 sản phẩm mới nhất từ csdl
- Lưu trữ: không có

**Comment by obito0147** [comment]
đã nhận

**Comment by obito0147** [comment]
đã hoàn thành
