### ISSUE TITLE
30. Xem danh sách khách hàng (Admin)

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#31]
Giao diện: Một list thông tin khác hàng sẽ hiện ra bên cột bên phải của trang gồm các thông tin cơ bản của khách hàng như tên khách hàng, số điện thoại, địa chỉ, ngày sinh

Xử lý: sau khi bạn click vào mục danh sách khách hàng trong mục quản lý khách hàng nằm bên trái giao diện thì giao diện danh sách khách hàng sẽ được hiển thị

Lưu trữ: không có

**Comment by admd1142** [comment]
Giao diện: Một list thông tin khác hàng sẽ hiện ra bên cột bên phải của trang gồm các thông tin cơ bản của khách hàng như tên khách hàng, số điện thoại, địa chỉ, ngày sinh

Xử lý: sau khi bạn click vào mục danh sách khách hàng trong mục quản lý khách hàng nằm bên trái giao diện thì giao diện danh sách khách hàng sẽ được hiển thị

Lưu trữ: không có

**Comment by admd1142** [comment]
đã nhận!

**Comment by admd1142** [comment]
đã hoàn thành
