### ISSUE TITLE
31. Hủy đơn hàng

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#32]
- Giao diện: kế bên mỗi đơn hàng có một button "Hủy", khi click vào button sẽ chuyển tới trang xác nhận hủy đơn hàng bao gồm các thông tin (mã đơn hàng, tên khách hàng), bên dưới phần thông tin có 1 button "Xóa" để submit.
- Xử lý: khi click button "Xóa", đơn hàng sẽ được xóa khỏi danh sách dựa vào index.
- Lưu trữ: xóa đơn hàng trên CSDL.

**Comment by lamtrungnghia1202** [comment]
Đã hoàn thành
