### ISSUE TITLE
33. Xem danh sách tài khoản (Admin)

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#34]
Giao diện: Nằm trong mục quản lý khách hàng, giao diện quản lí khách hàng sẽ được hiển thị bên phải giao diện dưới dạng danh sách với các thuộc tính khác nhau (Tên đăng nhập, Mật khẩu, Tên, Ngày Sinh, Địa chỉ, SĐT)

Xử lý: Khi click vào danh sách tài khoản nằm trong mục quản lý khách hàng bên trái giao diện thì giao diện danh sách tài khoản sẽ hiển thị, dữ liệu sẽ được đọc từ database

Lưu trữ: Không có

**Comment by admd1142** [comment]
Giao diện: Nằm trong mục quản lý khách hàng, giao diện quản lí khách hàng sẽ được hiển thị bên phải giao diện dưới dạng danh sách với các thuộc tính khác nhau (Tên đăng nhập, Mật khẩu, Tên, Ngày Sinh, Địa chỉ, SĐT)

Xử lý: Khi click vào danh sách tài khoản nằm trong mục quản lý khách hàng bên trái giao diện thì giao diện danh sách tài khoản sẽ hiển thị, dữ liệu sẽ được đọc từ database

Lưu trữ: Không có

**Comment by admd1142** [comment]
đã nhận!

**Comment by admd1142** [comment]
đã hoàn thành
