### ISSUE TITLE
34. Xóa tài khoản (Admin)

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#35]
- Giao diện: Ở giao diện danh sách khách hàng hiển thị theo dạng danh sách thì mỗi dòng sẽ có button xóa. Khi click vào sẽ tiến hành xóa
- Xử lý: Load tài khoản khách hàng từ csdl lên giao diện, khi click vào button xóa sẽ tiến hành xóa tài khoản khách hàng
- Lưu trữ: Khi xóa tài khoản khách hàng dữ liệu của khách hàng đo dưới csdl sẽ bị xóa và lưu lại csdl

**Comment by obito0147** [comment]
đã nhận

**Comment by obito0147** [comment]
đã hoàn thành
