### ISSUE TITLE
3. Thêm sản phẩm vào giỏ hàng

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#4]
1. Giao diện:

- Trang chi tiết sản phẩm có được chia thành 2 column chính. Column bên trái hiển thị hình ảnh sản phẩm.
- Column phải hiên thị thông tin của sản phẩm. Có button “Mua ngay” ngay sau thông tin sản phẩm.

2. Xử lý:

- Khi click button “Mua ngay”. Sản phẩm sẽ được thêm vào List<CartItem>. Nếu trong List đã tồn tại sản phẩm, tăng số lượng sản phẩm lên thêm 1 lần. Nếu như chưa tồn tại thì Add sản phẩm vào List.

3. Lưu trữ

- List<CartItem> được lưu trữ trong phiên làm việc bằng Session.

**Comment by ChiCuong002** [comment]
Đã hoàn thành.
