### ISSUE TITLE
4. Xem danh sách đơn hàng (QLĐH)

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#5]
- Giao diện: sau khi đăng nhập thì giao diện đầu tiên là danh sách đơn đặt hàng, được hiển thị theo dạng table gồm các thông tin (mã đơn hàng, tên khách hàng, số điện thoại, số tiền, trạng thái thanh toán, ngày tạo đơn hàng, trạng thái giao hàng), phía bên phải ngoài cùng có 3 button (xem chi tiết đơn hàng, cập nhật, hủy đơn hàng), phía trên table danh sách đơn hàng có 1 khung tìm kiếm đơn hàng.
- Xử lí: sử dụng vòng lặp foreach để đọc dữ liệu của từng thông tin đon hàng, khi click vào button "Chi tiết" sẽ chuyển tới trang chi tiết đơn hàng, khi click vào button "Cập nhật " sẽ hiển thị dialog cập nhật, khi click vào button "Hủy" sẽ chuyển tới trang hỏi xác nhận để xóa, chức năng tìm kiếm và load các đơn hàng từ csdl theo từ khóa tìm kiếm.
- Lưu trữ: không có

**Comment by lamtrungnghia1202** [comment]
Đã hoàn thành
