### ISSUE TITLE
5. Xem danh sách sản phẩm (Admin)

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#6]
Giao diện: Nằm trong mục quản lý sản phẩm, giao diện quản lý sản phẩm sẽ hiển thị bên phải giao diện dưới dạng danh sách với các thuộc tính khác nhau (mã sản phẩm, tên sản phẩm)

Xử lý: Khi click vào danh sách sản phẩm trong mục quản lý sản phẩm bên trái giao diện thì giao diện danh sách sản phẩm sẽ được hiển thị. Dữ liệu hiển thị được truy cập từ database

Lưu trữ: Không có

**Comment by admd1142** [comment]
Giao diện: Nằm trong mục quản lý sản phẩm, giao diện quản lý sản phẩm sẽ hiển thị bên phải giao diện dưới dạng danh sách với các thuộc tính khác nhau (mã sản phẩm, tên sản phẩm, ….)

Xử lý: Khi click vào danh sách sản phẩm trong mục quản lý sản phẩm bên trái giao diện thì giao diện danh sách sản phẩm sẽ được hiển thị. Dữ liệu hiển thị được truy cập từ database

Lưu trữ: Không có

**Comment by admd1142** [comment]
đã hoàn thành
