### ISSUE TITLE
7. Xem danh sách sản phẩm 

### ISSUE THREAD

**Issue by Windyyyyyyyyy** [ChiCuong002/Website_BanDienThoaiDiDong#8]
Giao diện: khi chọn mục sản phẩm ở thanh navigation sẽ hiển thị trang danh sách sản phẩm. Phía dưới là một slider để quảng cáo. Phía dưới góc bên trái là danh mục các hãng cửa trang web khi (samsung,apple,xiaomi,oppo). góc bên phải là thanh tìm kiếm phía dưới thanh tìm kiếm là mục sắp xếp sản phẩm theo mục đã chọn
Xử lý: Load dữ liệu các hãng lên giao diện, khi chọn một hãng sẽ load tất cả sản phẩm của hãng đó lên giao diện, nhập dữ liệu tìm kiếm và load dữ liệu theo từ khóa đã nhập, sắp xếp sản phẩm theo mục đã chọn
Lưu trữ: Không có

**Comment by obito0147** [comment]
đã nhận

**Comment by obito0147** [comment]
đã hoàn thành
